config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'home', to: "pages#home", as: :home
  resources :users

  resources :items

  resources :deals do
    post "accept_deal", to: "deals#accept_deal"
    post "reject_deal", to: "deals#reject_deal"
    resources :deal_items
    resources :payments, only: [:new, :create]
  end

  resources :items do
    resources :deal_items
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :items, dependent: :destroy
  has_many :requested_deals, class_name: "Deal", foreign_key: "requester_id"
  has_many :answered_deals, class_name: "Deal", foreign_key: "answerer_id"

  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :trackable, :validatable
  validates :email, presence: true
  validates :name, presence: true
  mount_uploader :photo, PhotoUploader


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :find_user, only: [:show, :edit, :update, :destroy]

  def show
    @deal = Deal.new
    @deal.requester_id = current_user.id
    #@requester = User.find(current_user.id)
    #@deal.answerer_id = @item.user.id
  end

  def edit
    redirect_to root_path if @user != current_user
  end

  def update
    @user = current_user
    if @user.update(user_params)
      sign_in(current_user, :bypass => true)
      flash[:notice] ='Details successfully updated!'
      redirect_to user_path(current_user)
    else
      render :edit
    end
  end

  def destroy
    @user.destroy
    redirect_to root_path
  end

  private

  def user_params
    params.require(:user).permit(:name, :address, :email, :description, :password, :photo)
  end

  def find_user
    @user = User.find(params[:id])
    authorize @user
  end

end

app/views/users/_dashboard.html.erb
<div class="banner" style="background-image: linear-gradient(-225deg, rgba(0,50,50,0.1) 0%, rgba(0,36,61,0.3) 30%), url('https://images.unsplash.com/photo-1502727135886-df285cc8379f?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=6182683b9eb37511afe1ad1c3576e75a&auto=format&fit=crop&w=1050&q=80');">
</div>
<div class="container first-div">
  <div class="row">
    <div class="col-xs-4">
      <div class="profile-left">
        <div class="deal-avatar-box">
          <% if current_user.photo.present? %>
            <% url = cl_image_path current_user.photo%>
          <% else %>
            <% url = cl_image_path "defaultavatar.png" %>
          <% end %>
          <div class="deal-avatar" style="background-image: url(<%= url %>)"></div>
        </div>
        <div class="deal-user-information">
          <h4><%= current_user.name.upcase %></h4>
          <hr>
          <p><%= simple_format current_user.description %></p>
          <hr>
          <%= link_to "Edit profile", edit_user_path(@user) %>

        </div>
      </div>
    </div>
    <div class="col-xs-8">
      <div class="profile-right">
        <div class="deal-box">
          <ul class="nav nav-tabs">
              <li class="active tab-color"><a data-toggle="tab" href="#my_items">My Items</a></li>
              <li class="non-active-tab-color"><a data-toggle="tab" href="#my_deals">My Deals</a></li>
          </ul>
           <div class="tab-content">
            <div id="my_items" class="deal-tab tab-pane fade in active">
              <div class="deal-item-container">
                <% current_user.items.each do |item| %>
                  <%= link_to item_path(item), :class => "rent-link" do %>
                    <div class="deal-item-box box-card-profile" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)),
                          url(<%= cl_image_path item.photo, crop: :fill if item.photo.present? %>);">
                    </div>
                    <% end %>
                <% end %>
                <%= link_to new_item_path do %>
                  <div class="deal-item-box box-card-profile new-item-btn" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2));">
                    <span>+</span>
                  </div>
                <% end %>
              </div>
            </div>
            <div id="my_deals" class="deal-tab tab-pane fade">
              <div>
                <div class="deal-details">
                  <% if (@user.requested_deals.count == 0) && (@user.answered_deals.count == 0) %>
                    <div class="deal-btn">
                      <p style="margin-left:  10px; padding:  20px;">You do not have any deal</p>
                          <%= link_to items_path do %>
                            <p style="margin-left:  10px; padding:  20px; text-decoration: none; color: #616668; opacity: .6;">Click to browse</p>
                          <% end %>
                        </div>
                  <% else %>
                    <div class="deal-details-content">
                      <div class="involved-person">
                        <h4>Deal with</h4>
                      </div>
                      <div class="deal-status">
                        <h4>Status</h4>
                      </div>
                      <div class="deal-items-number">
                        <h4>Who pays?</h4>
                      </div>
                      <div class="deal-items-num">
                        <h4>No of items</h4>
                      </div>
                      <div class="deal-btn"></div>
                    </div>
                    <% current_user.requested_deals.each do |deal| %>
                      <div class="deal-details-content">
                        <div class="involved-person">
                          <% if deal.answerer.photo.present? %>
                            <%= cl_image_tag deal.answerer.photo, class: "mini-dashboard-avatar" %>
                          <% else %>
                            <%= cl_image_tag "defaultavatar.png", class: "mini-dashboard-avatar"  %>
                          <% end %>
                          <%#= deal.answerer.photo %>
                        </div>
                        <div class="deal-status">
                          <p><%= deal.status %></p>
                        </div>
                        <div class="deal-items-number">
                          <% if deal.price.fractional == 0 %>
                            <p>No one!</p>
                          <% else %>
                            <p><%= User.find(deal.payer.to_i).name %>!</p>
                          <% end %>
                        </div>
                        <div class="deal-items-num">
                          <p><%= deal.deal_items.count %></p>
                        </div>
                        <div class="deal-btn">
                          <%= link_to deal_path(deal) do %>
                            <i class="fa fa-eye"></i>
                          <% end %>
                        </div>
                      </div>
                    <% end %>
                    <% current_user.answered_deals.each do |deal| %>
                      <div class="deal-details-content">
                        <div class="involved-person">
                          <% if deal.requester.photo.present? %>
                            <%= cl_image_tag deal.requester.photo, class: "mini-dashboard-avatar" %>
                          <% else %>
                            <%= cl_image_tag "defaultavatar.png", class: "mini-dashboard-avatar"  %>
                          <% end %>
                          <%#= deal.requester.photo %>
                        </div>
                        <div class="deal-status">
                          <p><%= deal.status %></p>
                        </div>
                        <div class="deal-items-number">
                          <% if deal.price.fractional == 0 %>
                            <p>No one!</p>
                          <% else %>
                            <p><%= User.find(deal.payer.to_i).name %>!</p>
                          <% end %>
                        </div>
                        <div class="deal-items-num">
                          <p><%= deal.deal_items.count %></p>
                        </div>
                        <div class="deal-btn">
                          <%= link_to deal_path(deal) do %>
                            <i class="fa fa-eye"></i>
                          <% end %>
                        </div>
                      </div>
                    <% end %>
                  <% end %>
                </div>
              </div>
            </div>
          </div>
        </div>
        </div>
      </div>
    </div>
  </div>
 </div>

app/views/users/_form.html.erb
<%= simple_form_for(@user) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :email %>
    <%= f.input :password %>
    <%= f.input :description %>
    <%= f.input :photo %>
    <%= f.input :photo_cache, as: :hidden %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, class: "exs-btn btn-submit"%>
  </div>
<% end %>

app/views/users/_make_a_deal.html.erb
<div class="makedeal-photo">
  <% if current_user.photo.present? %>
    <%= cl_image_tag current_user.photo, class: "dashboard-avatar" %>
  <% else %>
    <%= cl_image_tag "defaultavatar.png", class: "dashboard-avatar"  %>
  <% end %>
  <% if user.photo.present? %>
    <%= cl_image_tag user.photo, class: "dashboard-avatar" %>
  <% else %>
    <%= cl_image_tag "defaultavatar.png", class: "dashboard-avatar"  %>
  <% end %>
</div>

<%= simple_form_for(deal) do |f| %>
  <%= f.input :answerer_id, as: :hidden, input_html: { value: user.id }%>

  <%= f.simple_fields_for :deal_items do |p| %>
    <div class="content-row flex">
      <div class="content-column">
        <h1 class="dash-text text-center">YOU</h1>
        <% current_user.items.each do |item| %>
          <input type="hidden" name="deal[deal_items][my_item_id][]" value="">
          <label class="box-content" for="deal_deal_items_my_item_id_<%= item.id %>">
          <div class="box-card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)),
                    url(<%= cl_image_path item.photo, crop: :fill if item.photo.present? %>);">
            <i class= "fa fa-check"></i>
          </div>
          </label>
            <input class="hidden" type="checkbox" value="<%= item.id %>" name="deal[deal_items][my_item_id][]" id="deal_deal_items_my_item_id_<%= item.id %>">

          <% end %>
      </div>
      <div class="content-column" >

        <h1 class="dash-text text-center"><%= user.name %></h1>
        <% user.items.each do |item| %>
          <input type="hidden" name="deal[deal_items][item_id][]" value="">
          <label class="box-content" for="deal_deal_items_item_id_<%= item.id %>">
            <div class="box-card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)),
                    url(<%= cl_image_path item.photo, crop: :fill if item.photo.present? %>);">
              <i class= "fa fa-check"></i>
            </div>
          </label>
          <input class="hidden" type="checkbox" value="<%= item.id %>" name="deal[deal_items][item_id][]" id="deal_deal_items_item_id_<%= item.id %>">
        <% end %>
      </div>
    </div>
  <% end %>

    <div class="content-row">

      <h1 class="text-center" style="color: #2C2C2C;">WHAT ABOUT MONEY?</h1>

    </div>

    <%= f.simple_fields_for :payer do |p| %>

    <div class="content-row flex">
      <div class="content-column text-center">
        <input class="" type="radio" value="<%= current_user.id %>" name="deal[payer]" id="deal_payer_give">
        <label for="deal_payer_give" style="color: #2C2C2C;">
          I'm giving you...
        </label>
      </div>

      <div class="content-column text-center">
        <input class="" type="radio" value="<%= @user.id %>" name="deal[payer]" id="deal_payer_recieve">
        <label for="deal_payer_recieve" style="color: #2C2C2C;">
          Can you give me?
        </label>
      </div>
      </div>
    <% end %>
    <div class="content-row text-center">
      <div class="form-group string optional deal_price">
        <input class="form-control string optional" type="text" value="0" name="deal[price]" id="deal_price" placeholder="£">
      </div>
    </div>
    <div class="content-row text-center">
      <%= f.submit "SEAL THE DEAL", class: "btn btn-deal" %>
    </div>
    <!-- queryselectorall the cards -->
    <!-- AddEventListener to click. -->
    <!-- the you check the class list of each card to see if they clicked a card  -->
    <!-- then you your conditions -->
      <!-- if one_is_selected on the right && one is selected on the right -->
        <!-- add class not-blurred -->

      <!-- HOW DO WE KNOW IF THEY HAVE TYPED IN MONTY? -->
        <!-- add event listener on the form for keypress -->
      <!-- if one_is_selcetd on the right && you put in some money, -->
        <!-- add class not-blurred -->
      <!-- else -->
        <!-- dont change the blur -->
      <!-- end -->
    <%#= render "make_a_deal", deal: @deal, user: @user %>

<% end %>

app/views/users/edit.html.erb
<div class="editprofile-box">
  <div class="editprofile-background" style="background-image: url('https://images.unsplash.com/photo-1501349800519-48093d60bde0?ixlib=rb-0.3.5&s=c42f57ee27eaef62a8b49335d1f13ab5&auto=format&fit=crop&w=750&q=80');">
    <div class="editprofile-image" style="width: 40%; height: 200px; background-image: url(<%= image_path @user.photo, height: 200 %>); background-size: cover">
    </div>
  </div>
  <div class="editprofile-form">
    <center><h3> Edit Profile</h3></center>
    <%= render 'form', user: @user %>
  </div>
</div>

app/views/users/show.html.erb
<!-- display when the user != current_user -->
<% if @user != current_user %>
  <%= render "make_a_deal", deal: @deal, user: @user %>

<!-- display when the user == current_user -->
<% else %>
  <%= render "dashboard" %>
 <!-- end belong to else -->
<% end %>





















































<%= javascript_pack_tag "choice" %>