config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'home', to: "pages#home", as: :home
  resources :users

  resources :items

  resources :deals do
    post "accept_deal", to: "deals#accept_deal"
    post "reject_deal", to: "deals#reject_deal"
    resources :deal_items
    resources :payments, only: [:new, :create]
  end

  resources :items do
    resources :deal_items
  end

end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div id="wrapper">
  <div class="footer">
    <div class="footer-copyright">
      <i class="fa fa-copyright"></i> EX$ Team SAVA 2018
    </div>
    <div class="footer-links">
      <a><i class="fa fa-instagram"></i></a>
      <a><i class="fa fa-facebook-f"></i></a>
      <a><i class="fa fa-twitter"></i></a>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "newdlogo.jpg", height: 350 %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <% if user_signed_in? %>

      <!-- Links when logged in -->
      <%= link_to "Profile", user_path(current_user), class: "navbar-wagon-item navbar-wagon-link" %>

      <!-- Avatar with dropdown menu -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <%# image_tag "http://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <% if current_user.photo.present? %>
            <%= cl_image_tag current_user.photo, class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <% else %>
              <%= image_tag "defaultavatar.png", class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <% end %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>

              <%= link_to edit_user_path(current_user) do%>

                <i class="fa fa-user"></i> <%= t(".profile", default: "Edit Profile") %>
              <% end %>
            </li>
            <li>
              <%= link_to new_item_path do %>
                <i class="fa fa-plus-square"></i>  <%= t(".settings", default: "List Items") %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>
    <% else %>

      <!-- Login link (when logged out) -->
      <div class="options">
        <a href="#" class="navbar-wagon-item navbar-wagon-link" data-toggle="modal" data-target="#signUpModal">Sign Up</a>
        <a href="#" class="navbar-wagon-item navbar-wagon-link" data-toggle="modal" data-target="#logInModal">Log In</a>
      </div>
    <% end %>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <% if user_signed_in? %>
    <div class="navbar-wagon-item hidden-md hidden-lg">
      <div class="dropdown">
        <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
        <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
          <li>
            <%= link_to user_path(current_user) do %>
              <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
            <% end %>
          </li>
          <li>
            <%= link_to new_item_path do %>
              <i class="fa fa-plus-square"></i>  <%= t(".settings", default: "List Items") %>
            <% end %>
          </li>
          <li>
            <%= link_to destroy_user_session_path, method: :delete do %>
              <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
            <% end %>
          </li>
        </ul>
      </div>
    </div>
  </div>
  <% else %>
  <div class="navbar-wagon-item hidden-md hidden-lg">
      <div class="dropdown">
        <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
        <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
          <li>
            <a href="#" class="navbar-wagon-item navbar-wagon-link" data-toggle="modal" data-target="#logInModal">Log In</a>
          </li>
          <li>
            <a href="#" class="navbar-wagon-item navbar-wagon-link" data-toggle="modal" data-target="#signUpModal">Sign up</a>
          </li>
        </ul>
      </div>
  </div>
  <% end %>
</div>

 <!-- Modal -->
<!-- Sign up Modal -->
<div class="modal fade" id="signUpModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <button type="button" class="close-button" data-dismiss="modal">[x]</button>
  <div class="br">
    <div class="modal-cont">
      <div class="modal-content">
        <ul class="nav nav-tabs modal-styling" id="myTab" role="tablist">
          <li class="active-tab active"><a href="#signup" data-toggle="tab">Sign Up</a></li>
          <li class="non-active-tab"><a href="#login" data-toggle="tab">Log In</a></li>
        </ul>
        <div class="tab-content" id="myTabContent">
          <div class="tab-pane fade active in" id="signup" role="tabpanel" aria-labelledby="home-tab">
            <%= render "devise/registrations/new" %>
          </div>
          <div class="tab-pane fade in" id="login" role="tabpanel" aria-labelledby="profile-tab">
            <%= render "devise/sessions/new" %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<!-- Login Modal -->
<div class="modal fade" id="logInModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <button type="button" class="close-button" data-dismiss="modal">[x]</button>
  <div class="modal-cont">
    <div class="modal-content">
      <ul class="nav nav-tabs modal-styling " id="yourTab" role="tablist">
        <li class="non-active-tab"><a href="#signit" data-toggle="tab">Sign Up</a></li>
        <li class="active-tab active"><a href="#logit" data-toggle="tab">Log In</a></li>
      </ul>
      <div class="tab-content" id="yourTabContent">
        <div class="tab-pane fade in" id="signit" role="tabpanel" aria-labelledby="home-tab">
          <%= render "devise/registrations/new" %>
        </div>
        <div class="tab-pane fade active in" id="logit" role="tabpanel" aria-labelledby="profile-tab">
          <%= render "devise/sessions/new" %>
        </div>
      </div>
    </div>
  </div>
</div>