config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'home', to: "pages#home", as: :home
  resources :users

  resources :items

  resources :deals do
    post "accept_deal", to: "deals#accept_deal"
    post "reject_deal", to: "deals#reject_deal"
    resources :deal_items
    resources :payments, only: [:new, :create]
  end

  resources :items do
    resources :deal_items
  end

end

app/models/deal.rb
class Deal < ApplicationRecord
  belongs_to :requester, class_name: 'User', foreign_key: 'requester_id'
  belongs_to :answerer, class_name: 'User', foreign_key: 'answerer_id'
  monetize :price_cents
  has_many :deal_items, dependent: :destroy
  has_many :items, through: :deal_items

  def items_from(user)
    self.items.where(user_id: user.id)
  end
end

app/controllers/deals_controller.rb
class DealsController < ApplicationController
  before_action :find_deal, only: [:show, :edit, :update, :destroy]

  def show
    @payer = User.find(@deal.payer.to_i)
  end

  def new
    # @deal = Deal.new
  end

  def create
    # @item = Item.find(params[:deal][:item_ids])
    @deal = Deal.new(deal_params)
    @deal.status = "In negotiation"
    @deal.requester_id = current_user.id
    authorize @deal
    if @deal.save
      create_deal_items(params[:deal][:deal_items][:item_id], params[:deal][:deal_items][:my_item_id], @deal)
      redirect_to deal_path(@deal)
    else
      render :new
    end
  end

  def edit
  end

  def update
    @deal.answerer_address = params[:deal][:answerer_address] unless params[:deal][:answerer_address].nil?
    @deal.requester_address = params[:deal][:requester_address] unless params[:deal][:requester_address].nil?
    @deal.update(deal_params)
    redirect_to deal_path(@deal)
  end

  def destroy
    @deal.destroy
    redirect_to user_path(current_user)
  end

  def accept_deal
    @deal = Deal.find(params[:deal_id])
    authorize @deal
    @deal.status = "Finalised"
    #@deal.last_changed_by = current_user.id
    @deal.save
    redirect_to deal_path(@deal)
  end

  def reject_deal
    @deal = Deal.find(params[:deal_id])
    authorize @deal
    @deal.status = "In negotiation"
    @deal.save
    redirect_to deal_path(@deal)
  end

  private

  def create_deal_items(ids_of_answerer, ids_of_requester, deal)
    clean_ids = ids_of_answerer&.reject { |c| c.empty? }
    clean_my_ids = ids_of_requester&.reject { |c| c.empty? }

    clean_ids&.each do |id|
      DealItem.create(item_id: id, deal: deal)
    end
    clean_my_ids&.each do |id|
      DealItem.create(item_id: id, deal: deal)
    end
  end

  def deal_params
    params.require(:deal).permit(:answerer_id, :price, :payer, :answerer_address, :requester_address)
  end

  def find_deal
    @deal = Deal.find(params[:id])
    authorize @deal
  end



end

app/views/deals/_form.html.erb
<%= simple_form_for(@deal) do |f| %>
  <%= f.error_notification %>
  <div class="form-inputs">
    <%= f.input :price %>
    <%= f.input :payer, collection: [@deal.answerer.email, @deal.requester.email] %>
  </div>
  <div class="form-actions">
    <%= f.button :submit, class: "exs-btn btn-submit" %>
  </div>
<% end %>

app/views/deals/_form2.html.erb
<%= simple_form_for(@deal, :url => deal_path(@deal)) do |f| %>
  <%= f.error_notification %>
  <div class="form-inputs">
    <%= f.input :answerer_address, label: "My address", placeholder: "where's convenient?" %>
  </div>
  <div class="form-actions">
    <%= f.button :submit, class: "exs-btn btn-submit", id: "form2-submit-button" %>
  </div>
<% end %>

app/views/deals/show.html.erb
<!-- Deal announcement and status -->
<center>
  <h1 style="text-align: center">It's a deal!</h1>
  <% if @deal.status == "In negotiation" && @deal.requester != current_user %>
    <div class="deal-payment-content-row flex deal-middle-page">
      <%= button_to "Accept", deal_accept_deal_path(@deal), class: "exs-btn btn-submit" %>
    </div>
  <% elsif @deal.status == "In negotiation" %>
    <div class="deal-payment-content-row flex deal-middle-page">
      <h4>Still waiting for <%= @deal.answerer.name %> to confirm...</h4>
    </div>
  <% else %>
    <div class="deal-payment-content-row flex deal-middle-page">
      <h4>You've both agreed to this deal!</h4>
    </div>
  <% end %>
</center>

<!-- Items in the deal and payment button -->
<!-- requester view -->
<% if current_user == @deal.requester %>
  <div class="content-row flex">
    <div class="content-column">
      <h3 class="text-center">You're sending <%= @deal.answerer.name %>...</h3>
      <% @deal.items.each do |item| %>
        <% if item.user == current_user %>
          <label class="box-content" for="deal_deal_items_my_item_id_<%= item.id %>">
            <div class="box-card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)),
                  url(<%= cl_image_path item.photo, crop: :fill if item.photo.present? %>);">
            </div>
          </label>
        <% end %>
      <% end %>
    </div>
    <div class="content-column">
      <h3 class="text-center"><%= @deal.answerer.name %>'s sending you...</h3>
      <% @deal.items.each do |item| %>
        <% if item.user != current_user %>
          <label class="box-content" for="deal_deal_items_item_id_<%= item.id %>">
            <div class="box-card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)),
                  url(<%= cl_image_path item.photo, crop: :fill if item.photo.present? %>);">
            </div>
          </label>
        <% end %>
      <% end %>
    </div>
  </div>
  <!-- price below -->
  <% if @deal.price.fractional != 0 %>
    <div class="deal-payment-content-row flex deal-middle-page">
      <div class="content-column">
        <% if current_user != @payer %>
          <p style="text-align: center"><%= @deal.answerer.name %> is also going to pay you £<%= @deal.price %></p>
        <% else %>
          <p style="text-align: center">You also need to pay <%= @deal.answerer.name %> £<%= @deal.price %></p>
        <% end %>
        <% if (current_user == @payer) && (@deal.status == "Finalised") %>
          <%= button_to "Pay", deal_payments_path(@deal), class: "exs-btn btn-submit" %>
        <% end %>
      </div>
    </div>
  <% end %>

<!-- answerer view -->
<% elsif current_user == @deal.answerer %>
  <div class="content-row flex">
    <div class="content-column" >
      <h3 class="text-center">You're sending <%= @deal.requester.name %>...</h3>
      <% @deal.items.each do |item| %>
        <% if item.user == current_user %>
          <label class="box-content" for="deal_deal_items_item_id_<%= item.id %>">
            <div class="box-card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)),
                  url(<%= cl_image_path item.photo, crop: :fill if item.photo.present? %>);">
            </div>
          </label>
        <% end %>
      <% end %>
    </div>
    <div class="content-column">
      <h3 class="text-center"><%= @deal.requester.name %>'s sending you...</h3>
      <% @deal.items.each do |item| %>
        <% if item.user != current_user %>
          <label class="box-content" for="deal_deal_items_my_item_id_<%= item.id %>">
            <div class="box-card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)),
                  url(<%= cl_image_path item.photo, crop: :fill if item.photo.present? %>);">
            </div>
          </label>
        <% end %>
      <% end %>
    </div>
  </div>
  <!-- price below -->
  <% if @deal.price.fractional != 0 %>
    <div class="deal-payment-content-row flex deal-middle-page">
      <div class="content-column">
        <% if current_user == @payer %>
          <p style="text-align: center">You also need to pay <%= @deal.requester.name %> £<%= @deal.price %></p>
        <% else %>
          <p style="text-align: center"><%= @deal.requester.name %> is also going to pay you £<%= @deal.price %></p>
        <% end %>
        <% if (current_user == @payer) && (@deal.status == "Finalised") %>
          <%= button_to "Pay", deal_payments_path(@deal), class: "exs-btn btn-submit" %>
        <% end %>
      </div>
    </div>
  <% end %>
<% end %>

<!-- icons to return home or destroy -->
<center>
  <% if @deal.status == "In negotiation" && @deal.requester != current_user %>
    <div class="deal-payment-content-row flex deal-middle-page">
      <div class="content-column">
        <%= link_to "", user_path(current_user), class: "fa fa-arrow-left deal-arrow" %>
      </div>
      <div class="content-column">
        <% if @deal.status == "In negotiation" %>
          <%= link_to "", { controller: :deals, action: :destroy }, method: :delete, data: { confirm: "Don't want it?" }, class: "fa fa-trash deal-trash" %>
        <% else %>
          <%= link_to "", { controller: :deals, action: :destroy }, method: :delete, data: { confirm: 'Have you paid or received any money owed, and sent and received all the items?  This deal has been agreed' }, class: "fa fa-trash deal-trash" %>
        <% end %>
      </div>
    </div>
  <% elsif @deal.status == "In negotiation" %>
    <div class="deal-payment-content-row flex deal-middle-page">
      <div class="content-column">
        <%= link_to "", user_path(current_user), class: "fa fa-arrow-left deal-arrow" %>
      </div>
      <div class="content-column">
        <% if @deal.status == "In negotiation" %>
          <%= link_to "", { controller: :deals, action: :destroy }, method: :delete, data: { confirm: "Don't want it?" }, class: "fa fa-trash deal-trash" %>
        <% else %>
          <%= link_to "", { controller: :deals, action: :destroy }, method: :delete, data: { confirm: 'Have you paid or received any money owed, and sent and received all the items?  This deal has been agreed' }, class: "fa fa-trash deal-trash" %>
        <% end %>
      </div>
    </div>
  <% else %>
  <% end %>
</center>

<!-- address boxes (only visible if deal finalised or paid)-->
<!-- requester view -->
<center>
<% if (@deal.requester == current_user) && (@deal.status == "Finalised") %>
  <div class="deal-payment-content-row flex">
    <div class="content-column">
      <center><p>The address I want things sent to:</p>
      <h4><%= @deal.requester_address %></h4></center>
      <div class="section">
        <p>Change my postal address</p>
        <%= render "form" %>
      </div>
    </div>
    <div class="content-column">
      <center><p><%= @deal.answerer.email %>'s address:</p>
      <h4><%= @deal.answerer_address %></h4></center>
    </div>
  </div>
  <div class="deal-payment-content-row flex">
    <div class="content-column deal-middle-page">
      <%= link_to "", user_path(current_user), class: "fa fa-arrow-left deal-arrow" %>
    </div>
    <div class="content-column deal-middle-page">
        <% if @deal.status == "In negotiation" %>
          <%= link_to "", { controller: :deals, action: :destroy }, method: :delete, data: { confirm: "Don't want it?" }, class: "fa fa-trash deal-trash" %>
        <% else %>
          <%= link_to "", { controller: :deals, action: :destroy }, method: :delete, data: { confirm: 'Have you paid or received any money owed, and sent and received all the items?  This deal has been agreed' }, class: "fa fa-trash deal-trash" %>
        <% end %>
    </div>
  </div>

<!-- answerer view -->
<% elsif (@deal.answerer == current_user) && (@deal.status == "Finalised") %>
  <div class="deal-payment-content-row flex">
    <div class="content-column">
      <center><p>The address I want things sent to:</p>
      <h4><%= @deal.answerer_address %></h4></center>
      <div class="section">
        <p>Change my postal address</p>
        <%= render "form2" %>
      </div>
    </div>
    <div class="content-column">
      <center><p><%= @deal.requester.email %>'s address:</p>
      <h4><%= @deal.requester_address %></h4></center>
    </div>
  </div>
  <div class="deal-payment-content-row flex">
    <div class="content-column deal-middle-page">
      <%= link_to "", user_path(current_user), class: "fa fa-arrow-left deal-arrow" %>
    </div>
    <div class="content-column deal-middle-page">
      <% if @deal.status == "In negotiation" %>
        <%= link_to "", { controller: :deals, action: :destroy }, method: :delete, data: { confirm: "Don't want it?" }, class: "fa fa-trash deal-trash" %>
      <% else %>
        <%= link_to "", { controller: :deals, action: :destroy }, method: :delete, data: { confirm: 'Have you paid or received any money owed, and sent and received all the items?  This deal has been agreed' }, class: "fa fa-trash deal-trash" %>
      <% end %>
    </div>
  </div>
<% end %>
</center>
  <!-- end of address boxes code -->

<%= javascript_pack_tag 'form' %>
<%= javascript_pack_tag 'form2' %>