config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'home', to: "pages#home", as: :home
  resources :users

  resources :items

  resources :deals do
    post "accept_deal", to: "deals#accept_deal"
    post "reject_deal", to: "deals#reject_deal"
    resources :deal_items
    resources :payments, only: [:new, :create]
  end

  resources :items do
    resources :deal_items
  end

end

app/models/item.rb
class Item < ApplicationRecord
  # include PgSearch
  acts_as_votable
  # multisearchable against: [ :category, :description, :size, :color]
  include PgSearch
    pg_search_scope :search,
      against: [ :category, :description, :size, :color ],
      using: {
        tsearch: { prefix: true } # <-- now `superman batm` will return something!
      }
        pg_search_scope :searchsize, against: [:size]
    pg_search_scope :searchcategory, against: [:category]
    pg_search_scope :searchcolor, against: [:color]
  belongs_to :user
  has_many :deal_items, dependent: :destroy
  has_many :deals, through: :deal_items

  CATEGORIES = ["Dress", "Shoes", "Shirts", "Bags", "Blouse", "Skirt", "Trousers", "Suits", "Shirts", "Tuxedo"]
  validates :size, :color, :description, presence: :true
  validates :category, presence: true, inclusion: { in: CATEGORIES}
  validates :photo, presence: true
 mount_uploader :photo, PhotoUploader
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]
  before_action :find_item, only: [:show, :edit, :update, :destroy]

 def index
  @items = policy_scope(Item).order(created_at: :desc)

  # @items_index = Item.all
    puts params
    @categories = ["Dress", "Shoes", "Shirts", "Bags", "Blouse", "Skirt", "Trousers", "Suits", "Shirts", "Tuxedo"]
    # @items = policy_scope(Item).order(created_at: :desc)
    # search from the homepage
    @search = params[:search]
    if params[:search].present?
      @items = Item.search(params[:search])
    else
      @items = Item.all
    end
    #additional search filter from index
    if params[:item_size]
      @items = Item.search(params[:item_size][:search]).searchsize(params[:item_size][:size])
    end

    if params[:item_category]
      @items = Item.search(params[:item_category][:search]).searchcategory(params[:item_category][:category])
    end

    if params[:item_color]
      @items = Item.search(params[:item_color][:search]).searchcolor(params[:item_color][:color])
    end
  end

  def show
    @deal = Deal.new
    @item = Item.find(params[:id])
    @suggestions = Item.limit(3).where(category: "#{@item.category}").where(size: "#{@item.size}").where.not(id: "#{@item.id}")
  end

  def new
    @item = Item.new
    authorize @item
  end

  def create
    @item = Item.new(item_params)
    @item.user = current_user
    authorize @item
     if @item.save
      redirect_to item_path(@item)
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @item.update(item_params)
      redirect_to item_path(@item)
    else
      render :edit
    end  end

  def destroy
    @item = Item.find(params[:id])
    @item.destroy
    redirect_to user_path(current_user)
  end

  private

  def item_params
    params.require(:item).permit(:name,:item, :category, :size, :color, :description, :photo)
  end

  def find_item
    @item = Item.find(params[:id])
    authorize @item
  end
end

app/views/items/_form.html.erb
<%= simple_form_for(@item) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :category,collection: Item::CATEGORIES %>
    <%= f.input :size %>
    <%= f.input :color %>
    <%= f.input :description %>
    <%= f.input :photo %>
    <%= f.input :photo_cache, as: :hidden %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, class: "exs-btn btn-submit"%>
  </div>
<% end %>

app/views/items/edit.html.erb
<div class="editems-box">
  <div class="editem-image" style="width: 50%; height: 718px; background-image: url(<%= image_path @item.photo, height: 500 %>); background-size: cover">
  </div>


  <div class="editem-form">
    <center><h3> Edit Item</h3></center>
    <%= render 'form', item: @item %>
  </div>

<div class="delete-item">
  <div class="item-delete">
      <%= link_to 'Delete', { controller: :items, action: :destroy }, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-default" %>
  </div>
</div>
</div>

app/views/items/index.html.erb
<!-- <div class="container">
<%#= simple_form_for :item_category, url: items_path, method: :get do |f| %>
  <%#= f.input :category, :collection => @categories %>
  <%#= f.input :search, :as => :hidden, :input_html => { :value => @search} %>
  <%#= f.button :submit %>
<%# end %>

<%#= simple_form_for :item_size, url: items_path, method: :get do |f| %>
  <%#= f.input :size %>
  <%#= f.input :search, :as => :hidden, :input_html => { :value => @search} %>
  <%#= f.button :submit %>
<%# end %>

<%#= simple_form_for :item_color, url: items_path, method: :get do |f| %>
  <%#= f.input :color %>
  <%#= f.input :search, :as => :hidden, :input_html => { :value => @search} %>
  <%#= f.button :submit %>
<%# end %>
</div> -->




<div class=" indexcards container align-middle content">
  <div class="row">
    <% @items.each do |item| %>
    <div class="col-xs-12 col-sm-4">
      <%= link_to item_path(item), :class => "exchange-link" do %>
      <div class="card-position">
        <div class="card-homepage" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)),
      url(<%= cl_image_path item.photo, height: 300, width: 400, crop: :fill if item.photo.present? %>);">
          <div class="homepage-desc">
            <p> Xchange! </p>
            <h5><%= item.name %></h5>
          </div>
           <div class="ownerphoto-card">
            <% if item.user.photo.present? %>
              <%= cl_image_tag item.user.photo, class: "owner-avatar" %>
            <% else %>
              <%= image_tag "smiley.jpg", class: "owner-avatar" %>
          <% end %>
          </div>
        </div>
      </div>
    <%end%>
    </div>
    <%end%>
  </div>
</div>

app/views/items/new.html.erb
<div class="newitems-box">
  <div class="newitems-image" style="background-image: url('<%= cl_image_path 'clothes1.jpg' %>')">
  </div>

  <div class="newitem-form">
    <center><h3> List your item to exchange </h3></center>
    <%= render 'form', item: @item %>
  </div>

  <div class="newitems-image" style="background-image: url('<%= cl_image_path 'clothes2.jpg' %>')">
  </div>
</div>

app/views/items/show.html.erb
<% content_for :meta_title, "#{@item.name} is on #{DEFAULT_META["meta_product_name"]}" %>
<% content_for :meta_description, @item.description %>
<% content_for :meta_image, cl_image_path(@item.photo) %>

<div class="showitem-cont container">
  <!-- <div class="background" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('https://images.unsplash.com/photo-1470309864661-68328b2cd0a5?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=d7f4285ea420ec7ff9755dcf7500a8b1&auto=format&fit=crop&w=1650&q=80')"> -->

  <div id="item-content">
    <div class="showitem-left col-xs-12 col-md-6">
      <div class="showitem-photo" style="background-image: url('<%= cl_image_path @item.photo%>')">
      </div>
    </div>

    <div class="showitem-right col-xs-12 col-md-6">
      <h3 class="showitem-title"><%= @item.name %></h3>

      <!-- <button class="accordion">Show More Details</button>
      <div class="panel"> -->
      <p class="showitem-content"><strong>Category:</strong> <%= @item.category %></p>
      <p class="showitem-content"><strong>Size:</strong> <%= @item.size %></p>
      <p class="showitem-content"><strong>Color:</strong> <%= @item.color %></p>
      <p class="showitem-content"><strong>Description:</strong> <%= @item.description %></p>
     <!--  </div> -->
      <div class="showitem-buttons">
        <% if @item.user == current_user %>
          <%= link_to '', edit_item_path(@item), class: "fa fa-edit" %>
          <%= link_to '', { controller: :items, action: :destroy }, method: :delete, data: { confirm: 'Are you sure?' }, class: "fa fa-trash" %>
        <% else %>
          <%= link_to "Make a Deal", user_path(@item.user), class: "btn-make-deal" %>
        <% end %>
      </div>

      <h5 id="similar-item"> Other Items You'll Love:</h5>
      <div class="row">
        <% @suggestions.each do |suggestion| %>
          <div class="col-xs-12 col-md-4">
            <%= link_to item_path(suggestion) do %>
              <div class="suggestion-card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)),url('<%= cl_image_path suggestion.photo, class: "suggestion-image" %>');">
              </div>
            <% end %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>





<%= javascript_pack_tag 'show' %>